### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by dpmcgarry** [hadrsystems/nics-monitoring#2]
This project appears to depend on:
edu.mit.ll.nics.common:email-alert

The source is not in any project nor is the jar available on maven so this project build is broken (or the dep needs to be removed from the pom).

[ERROR] Failed to execute goal on project mach-core: Could not resolve dependencies for project edu.mit.ll.nics.monitoring:mach-core:jar:6.1: Could not find artifact edu.mit.ll.nics.common:email-alert:jar:6.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mach-core

**Comment by hadrsystemsteam** [comment]
Addressed in nics-common updates
