### ISSUE TITLE
Pom Issues

### ISSUE THREAD

**Issue by dpmcgarry** [hadrsystems/nics-monitoring#4]
Pom needs to specify character encoding or project may not be able to build:
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

Plugin versions were missing for the following:
in mach/pom.xml
maven-surefire-plugin
exec-maven-plugin

in mach-messages/pom.xml
maven-surefire-plugin

in host-ping-alert/pom.xml
maven-surefire-plugin

**Comment by hadrsystemsteam** [comment]
Addressed in POM updates
